### login
POST http://localhost:8080/employee/login
Content-Type: application/json

{
  "email": "ixti@gmail.com",
  "password": "123"
}

### Init admin
GET http://localhost:8080/employee/init

### Create employee
POST http://localhost:8080/employee/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3NjQzNTI3OTMsImVtYWlsIjoiYWpkbnMxQGRuLnNhIiwicm9sZSI6IkVNUExPWUVFIiwiZXhwIjoxNzY0NDM5MTkzLCJpc3MiOiJIUi1zeXN0ZW0ifQ.RuP4AUBfvnZ2lwHqsn-6y_F45s5xvj-vOMd2ILeqsUw2TGWrQMh97X8z2fM1cBofc6pC3h2yl16iTYoCVxtmfw

{
  "firstName": "name-1",
  "lastName": "name-2",
  "email": "aewe@dn.sa",
  "password": "12345",
  "position": "Ishchi",
  "salary": "100000"
}


### Update employee
PUT http://localhost:8080/employee/5
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3NjQzNTEyNTUsImVtYWlsIjoiaXh0aUBnbWFpbC5jb20iLCJyb2xlIjoiTUFOQUdFUiIsImV4cCI6MTc2NDQzNzY1NSwiaXNzIjoiSFItc3lzdGVtIn0.vMIYSAj4qQxE1rjTtNh64oP4TnWoAnwQ5mMXf9HvuSKU62o9_EqIh2jbOwT0DDrytjIY1P4-JltwW_RriDJfOw

{
  "firstName": "updated-name",
  "lastName": "updated-lastname",
  "position": "updated-position",
  "salary": "150000"
}

### Get By id
GET http://localhost:8080/employee/6
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3NjQzNTI3OTMsImVtYWlsIjoiYWpkbnMxQGRuLnNhIiwicm9sZSI6IkVNUExPWUVFIiwiZXhwIjoxNzY0NDM5MTkzLCJpc3MiOiJIUi1zeXN0ZW0ifQ.RuP4AUBfvnZ2lwHqsn-6y_F45s5xvj-vOMd2ILeqsUw2TGWrQMh97X8z2fM1cBofc6pC3h2yl16iTYoCVxtmfw

### Get all employee with pagination
GET http://localhost:8080/employee/
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3NjQzNTI3OTMsImVtYWlsIjoiYWpkbnMxQGRuLnNhIiwicm9sZSI6IkVNUExPWUVFIiwiZXhwIjoxNzY0NDM5MTkzLCJpc3MiOiJIUi1zeXN0ZW0ifQ.RuP4AUBfvnZ2lwHqsn-6y_F45s5xvj-vOMd2ILeqsUw2TGWrQMh97X8z2fM1cBofc6pC3h2yl16iTYoCVxtmfw

### Delete employee
DELETE http://localhost:8080/employee/5
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3NjQzNTEyNTUsImVtYWlsIjoiaXh0aUBnbWFpbC5jb20iLCJyb2xlIjoiTUFOQUdFUiIsImV4cCI6MTc2NDQzNzY1NSwiaXNzIjoiSFItc3lzdGVtIn0.vMIYSAj4qQxE1rjTtNh64oP4TnWoAnwQ5mMXf9HvuSKU62o9_EqIh2jbOwT0DDrytjIY1P4-JltwW_RriDJfOw

### Find by position name
GET http://localhost:8080/employee/position?positionName=admin
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3NjQzNTEyNTUsImVtYWlsIjoiaXh0aUBnbWFpbC5jb20iLCJyb2xlIjoiTUFOQUdFUiIsImV4cCI6MTc2NDQzNzY1NSwiaXNzIjoiSFItc3lzdGVtIn0.vMIYSAj4qQxE1rjTtNh64oP4TnWoAnwQ5mMXf9HvuSKU62o9_EqIh2jbOwT0DDrytjIY1P4-JltwW_RriDJfOw
Content-Type: application/json

### Search by name or surname
GET http://localhost:8080/employee/search?search=xabi
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3NjQzNTEyNTUsImVtYWlsIjoiaXh0aUBnbWFpbC5jb20iLCJyb2xlIjoiTUFOQUdFUiIsImV4cCI6MTc2NDQzNzY1NSwiaXNzIjoiSFItc3lzdGVtIn0.vMIYSAj4qQxE1rjTtNh64oP4TnWoAnwQ5mMXf9HvuSKU62o9_EqIh2jbOwT0DDrytjIY1P4-JltwW_RriDJfOw